;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        dired-toggle-read-only
        paredit-backward
        paredit-backward-kill-word
        paredit-doublequote
        paredit-forward
        paredit-forward-delete
        paredit-meta-doublequote
        paredit-open-round
        paredit-raise-sexp
        paredit-semicolon
        paredit-wrap-round
        slime-autodoc-space
        smex
        wdired-finish-edit
        wgrep-abort-changes
        ))

(setq mc/cmds-to-run-once
      '(
        ))
